site_name: KPN Theme
site_description: 'A KPN theme for MkDocs'

theme:
  name: kpn

repo_url: https://github.com/kpn/mkdocs-kpn-theme

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.critic
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
