site_name: KPN Theme
site_description: 'A KPN theme for MkDocs'
site_url: 'https://kpn.github.io/mkdocs-kpn-theme/'

theme:
  name: kpn

repo_name: 'kpn/mkdocs-kpn-theme'
repo_url: https://github.com/kpn/mkdocs-kpn-theme/

extra:
  version:
    provider: 'manual'
    version: 1.5.2

copyright: 'Copyright &copy; KPN'

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.critic
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - pymdownx.tabbed
plugins:
  - search:
      prebuild_index: true
